server {
    listen 80;
    server_name localhost;

    # 前端静态文件
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

     # 反向代理后端 API（匹配前端的 baseURL: /api）
     #proxy_pass http://backend:8080/api/ 中的 backend 是 docker-compose 中后端服务的名字，Docker 内部会自动解析
        location /api/ {
            proxy_pass http://backend:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

     # 上传文件代理（如果需要）
        location /uploads/ {
            proxy_pass http://backend:8080/uploads/;
        }


    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}

















